import type { Metadata } from "next";
import { Lexend_Deca } from "next/font/google";
import { Analytics } from '@vercel/analytics/react';
import { Toaster } from 'sonner'

import NavBar from "@/components/navbar";

import "./globals.css";

const lexend_deca = Lexend_Deca({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`${lexend_deca.className} w-11/12 sm:w-4/5 items-center content-center mx-auto pt-10 bg-[var(--bg-color)]`}>
        <NavBar></NavBar>
        {children}
        <Analytics></Analytics>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
